### ISSUE TITLE
Readwise Plugin: Sync All Error

### ISSUE THREAD

**Issue by EpistemicPolymath** [alloy-org/readwise#10]
I keep receiving this error every time I try to sync all after initial installation.

``Error: Cannot read properties of undefined (reading 'split') (line 887)``

**Comment by lukkes** [comment]
@EpistemicPolymath sorry for the late reply. Would it be possible to check if you are still seeing this issue after updating to the latest version of the plugin manually (from `https://amplenote.com/account/plugins`)? This would help narrow down the source of the error.

**Comment by EpistemicPolymath** [comment]
Sorry for the delay, I see you already closed this. I was without my computer for some time. I will re-open if I experience any issues with newer updates.
